PREFIX dc:<http://purl.org/dc/elements/1.1/>
PREFIX srbas:<http://gams.uni-graz.at/srbas/>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX psys:<http://proton.semanticweb.org/protonsys#>
PREFIX tei:<http://www.tei-c.org/ns/1.0>
PREFIX bk:<http://gams.uni-graz.at/rem/bookkeeping/>
PREFIX owl:<http://www.w3.org/2002/07/owl#>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX pext:<http://proton.semanticweb.org/protonext#>
PREFIX g2o:<http://gams.uni-graz.at/onto/#>
PREFIX bds: <http://www.bigdata.com/rdf/search#>
SELECT DISTINCT ?jahr ?von ?entry ?betrag ?text ?o ?signofamount ?konto ?pfad ("$1" as ?query)
WHERE {
    SERVICE <http://glossa.uni-graz.at/sesame/sparqlendpoint>
	{
       ?entry bk:inhalt ?text;
	       g2o:partOf ?o ;
	       bk:amount ?a .
	   ?a bk:num ?betrag ;
           bk:as ?signofamount .
       ?o dc:date ?jahr ;
           srbas:from ?von ;
           g2o:sameAs ?mo .
       $2 #;$2|...: wobei ... einem Constraint entspricht. Z.B. 
       # FILTER(regex(?text,"...","i")) # Regulärer Ausdruck
       # FILTER(regex(?text,"...1","i") && regex(?text, "...2", "i")) #  Regulärer Ausdruck auf einzelne Wörter
       # ?text bds:search "..." ;
       #    bds:matchAllTerms "true" . # Volltextsuche mit und-Verknüpfung
       # ??? Volltextsuche mit nicht-Verknüpfung
       # ??? Volltextsuche mit komplexer Syntax: oder/und/nicht kombiniert
       # FILTER(?jahr <= .... && ?jahr >= ...) # Zeitliche Einschränkung
       # ?konto bk:account <... Konto ...> . # Einschränkung auf Konto (incl. Unterkonten)
       # ??? Liste von Konten
       # FILTER(?betrag >= ...) # wobei der Vergleichsoperator mit übergeben wird
       #### All das wird in js/buildparams.js zusammengebaut
       OPTIONAL {
           ?entry bk:mainAccount ?konto .
           ?konto bk:accountPath ?pfad .
       }
	}
    SERVICE SILENT <http://glossa.uni-graz.at/mulgara/sparqlendpoint> {
       ?mo  <fedora-rels-ext:isMemberOf> <fedora:context:srbas> .
    }
}
ORDER BY ?jahr ?von ?o ?pfad ?entry
